---
- name: smoke test app
  hosts: localhost
  gather_facts: false

  tasks:
    - name: fetch app url 
      uri:
        url: http://frontend1.23e4.example.opentlc.com
        return_content: yes
        register: this
        failed_when: "'Ansible has done its job' not in this.content"